### ISSUE TITLE
License

### ISSUE THREAD

**Issue by frereit** [infertux/NAT-project#1]
Hello!

Would you mind adding a license to this project? I'd be interested in integrating this into a project I am working on.

Thanks!

**Comment by infertux** [comment]
Hi!

The source files already contain the `AGPL-3.0-or-later` header but I added a separate LICENSE file to make it more explicit.

Bear in mind that I wrote this code when I was learning C in school, I keep it mostly for archeological purpose and I wouldn't recommend to use it for anything serious ;)
